name: Hello World Pipeline
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run hello script
        run: bash hello.sh
